version: '3'

services:
  mailer:
    image: schickling/mailcatcher
    ports: [1025,1080]
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: toyrequest
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ROOT__USER: :root
    volumes:
      - db-data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
